#!/usr/bin/env python3
"""
RegVelo RNA velocity pipeline for VelocityBenchmarking (real data).

RegVelo extends veloVI with a gene regulatory network (GRN) prior. For real data
the prior is computed with pySCENIC (grn -> ctx -> aucell) and converted into a
0/1 regulator-target matrix; this script consumes either that pre-computed GRN
(``--grn-parquet``) or the pySCENIC AUCell loom (``--pyscenic-loom``) from which
the GRN is derived.

Installation:
    pip install regvelo scanpy scvelo GPUtil pynvml psutil pandas numpy scikit-learn
    pip install loompy pyarrow
    # A GPU-enabled PyTorch build is installed automatically as a dependency of regvelo.

Usage:
    # GRN parquet already generated by pySCENIC
    python RegVelo.py --input data.h5ad --output-dir ./output --cluster-key celltype \
        --grn-parquet regulon_mat_processed_all_regulons.parquet

    # Generate the GRN parquet from the pySCENIC AUCell loom, then run RegVelo
    python RegVelo.py --input data.h5ad --output-dir ./output --cluster-key celltype \
        --pyscenic-loom pyscenic_output.loom

    python RegVelo.py --metadata-file datasets.csv --output-dir ./output

Note:
    Simulated-data processing uses an a-priori GRN instead of pySCENIC and is kept
    in the separate RegVelo_sim.py script.
"""

from __future__ import annotations

import argparse
import gc
import os
import subprocess
import sys
import traceback
from pathlib import Path
from typing import List, Optional, Sequence

import matplotlib as mpl

mpl.use("Agg")
mpl.rcParams["pdf.fonttype"] = 42
mpl.rcParams["ps.fonttype"] = 42

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
import scvelo as scv

DEFAULT_N_TOP_GENES = 2000
_REGVELO_API = {}


# ---------------------------------------------------------------------------
# Environment / package helpers
# ---------------------------------------------------------------------------
def seed_everything(seed: int) -> None:
    import random

    random.seed(seed)
    np.random.seed(seed)
    try:
        import torch

        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
    except Exception:
        pass


def pick_free_gpu() -> int:
    """Return the physical GPU index with the most free memory (fallback: 0)."""
    try:
        out = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=index,memory.free", "--format=csv,noheader,nounits"],
            universal_newlines=True,
        )
        best_idx, best_free = 0, -1
        for line in out.strip().splitlines():
            parts = [part.strip() for part in line.split(",")]
            if len(parts) < 2:
                continue
            free = int(parts[1])
            if free > best_free:
                best_free = free
                best_idx = int(parts[0])
        return best_idx
    except Exception as exc:  # noqa: BLE001 - fall back to device 0
        print(f"[device] nvidia-smi query failed, using GPU 0: {exc}", file=sys.stderr)
        return 0


def configure_cuda(cuda: Optional[int]) -> Optional[str]:
    """Expose ``--cuda`` through ``CUDA_VISIBLE_DEVICES`` (never overrides the caller)."""
    if "CUDA_VISIBLE_DEVICES" in os.environ:
        return os.environ["CUDA_VISIBLE_DEVICES"]
    if cuda is None:
        cuda = pick_free_gpu()
    os.environ.setdefault("CUDA_VISIBLE_DEVICES", str(cuda))
    return os.environ.get("CUDA_VISIBLE_DEVICES")


def load_regvelo_api():
    """Import regvelo / torch lazily (after CUDA environment setup)."""
    if not _REGVELO_API:
        import torch
        import regvelo as rgv
        from regvelo import REGVELOVI

        _REGVELO_API.update(torch=torch, rgv=rgv, REGVELOVI=REGVELOVI)
    return _REGVELO_API


def cleanup_resources() -> None:
    gc.collect()
    plt.close("all")


# ---------------------------------------------------------------------------
# pySCENIC GRN handling
# ---------------------------------------------------------------------------
def detect_species(filename: str) -> str:
    """Detect the species token (``mm`` / ``hs``) from a file name."""
    tokens = filename.replace(".", "_").split("_")
    for token in tokens:
        lowered = token.lower()
        if lowered == "mm":
            return "mm"
        if lowered == "hs":
            return "hs"
        if lowered == "peripheral":
            return "hs"
    raise ValueError(f"Could not detect species from '{filename}' (expected 'Mm' or 'Hs')")


def convert_h5ad_to_loom(data_path, save_dir, data_file) -> Path:
    """Convert an h5ad file into the loom format consumed by pySCENIC."""
    import loompy  # noqa: F401 - imported for a clear error if missing

    adata = sc.read(data_path, cache=False)
    species = detect_species(data_file)

    adata_loom = sc.AnnData(adata.X, obs=adata.obs.copy(), var=adata.var.copy())
    adata_loom.var["Gene"] = adata_loom.var_names
    adata_loom.obs["CellID"] = adata_loom.obs_names

    save_dir = Path(save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)
    loom_path = save_dir / "adata.loom"
    adata_loom.write_loom(str(loom_path))
    (save_dir / "species.txt").write_text(species, encoding="utf-8")
    print(f"[INFO] loom written: {loom_path} (species={species})")
    return loom_path


def generate_grn_parquet(pyscenic_loom, parquet_out=None) -> Path:
    """Build the RegVelo GRN parquet from a pySCENIC AUCell output loom.

    Extracts the regulon-target matrix, binarizes it and writes a square 0/1
    ``genes x genes`` matrix. TF names are recovered from the regulon labels
    (e.g. ``"Sox10(+)"``) and duplicate regulons of the same TF are merged.
    """
    import loompy as lp

    pyscenic_loom = Path(pyscenic_loom)
    if parquet_out is None:
        parquet_out = pyscenic_loom.parent / "regulon_mat_processed_all_regulons.parquet"
    parquet_out = Path(parquet_out)

    if parquet_out.exists():
        print(f"[INFO] GRN parquet already exists: {parquet_out}")
        return parquet_out
    if not pyscenic_loom.exists():
        raise FileNotFoundError(f"pySCENIC AUCell loom not found: {pyscenic_loom}")

    csv_out = pyscenic_loom.parent / "regulon_mat_all_regulons.csv"

    lf = lp.connect(str(pyscenic_loom), mode="r+", validate=False)
    regulons = lf.ra.Regulons
    res = pd.concat(
        [pd.Series(r.tolist(), index=regulons.dtype.names) for r in regulons], axis=1
    )
    gene_names = lf.ra.Gene
    if gene_names.dtype.kind == "S":
        gene_names = np.array([g.decode("utf-8") for g in gene_names])
    res.columns = gene_names
    res.to_csv(csv_out)
    lf.close()
    print(f"[INFO] regulon matrix: {res.shape[0]} regulons x {res.shape[1]} genes")

    reg = pd.read_csv(csv_out, index_col=0)
    reg.index = reg.index.str.extract(r"(\w+)")[0]
    reg = reg.groupby(reg.index).sum()
    reg[reg != 0] = 1

    tfs = np.unique(reg.index.tolist())
    genes = np.unique(tfs.tolist() + reg.columns.tolist())
    grn = pd.DataFrame(0, index=genes, columns=genes)
    grn.loc[tfs, reg.columns.tolist()] = np.array(reg)

    mask = (grn.sum(0) != 0) | (grn.sum(1) != 0)
    grn = grn.loc[mask, mask].copy()
    grn.to_parquet(parquet_out)
    print(f"[INFO] GRN parquet: {parquet_out} ({grn.shape[0]} x {grn.shape[1]})")
    return parquet_out


def load_grn(grn_parquet=None, pyscenic_loom=None) -> pd.DataFrame:
    """Load the prior GRN matrix from a parquet file or a pySCENIC loom."""
    if grn_parquet is None:
        if pyscenic_loom is None:
            raise ValueError("Provide either --grn-parquet or --pyscenic-loom")
        grn_parquet = generate_grn_parquet(pyscenic_loom)
    grn = pd.read_parquet(grn_parquet)
    print(f"[INFO] prior GRN loaded from {grn_parquet}: {grn.shape}")
    return grn


# ---------------------------------------------------------------------------
# Preprocessing
# ---------------------------------------------------------------------------
def resolve_n_top_genes(n_vars: int, n_top_genes: int = DEFAULT_N_TOP_GENES) -> int:
    """Lower ``n_top_genes`` when the dataset has fewer genes (avoids IndexError)."""
    n_vars = int(n_vars)
    n_top_genes = int(n_top_genes)
    if n_vars >= n_top_genes:
        return n_top_genes
    new = ((n_vars - 1) // 100) * 100
    if new < 100:
        new = n_vars - 1
    new = max(1, int(new))
    print(f"[NTOP] {n_vars} genes < {n_top_genes}; using n_top_genes={new}")
    return new


def min_max_scale_layers(adata, layers: Sequence[str] = ("Ms", "Mu")) -> str:
    """Min-max scale the given layers (fallback when filter_genes is skipped)."""
    from sklearn.preprocessing import MinMaxScaler

    status = []
    for layer in layers:
        if layer not in adata.layers:
            status.append(f"{layer}:missing")
            continue
        arr = adata.layers[layer]
        if hasattr(arr, "toarray"):
            arr = arr.toarray()
        arr = np.asarray(arr)
        if arr.ndim != 2 or arr.shape[1] == 0:
            status.append(f"{layer}:skipped(no features)")
            continue
        adata.layers[layer] = MinMaxScaler().fit_transform(arr)
        status.append(f"{layer}:ok")
    return ", ".join(status)


def preprocess_adata(
    adata,
    grn: pd.DataFrame,
    cluster_key: str,
    n_top_genes: int = DEFAULT_N_TOP_GENES,
    n_pcs: int = 30,
    n_neighbors: int = 50,
    issue_log: Optional[str] = None,
    dataset_label: str = "",
):
    """Normalized RegVelo preprocessing (pySCENIC GRN prior + gene selection)."""
    api = load_regvelo_api()
    rgv = api["rgv"]

    if cluster_key != "clusters" and cluster_key in adata.obs.columns:
        adata.obs["clusters"] = adata.obs[cluster_key]

    scv.pp.filter_and_normalize(adata, min_shared_counts=20)
    n_top_genes = resolve_n_top_genes(adata.n_vars, n_top_genes)
    sc.pp.filter_genes_dispersion(adata, n_top_genes=n_top_genes)
    sc.pp.log1p(adata)
    if "neighbors" not in adata.uns:
        sc.pp.neighbors(adata, n_pcs=n_pcs, n_neighbors=n_neighbors)
    scv.pp.moments(adata, n_pcs=None, n_neighbors=None)

    # Inject the pySCENIC prior GRN (rows = targets, columns = regulators).
    adata = rgv.pp.set_prior_grn(adata, grn.T)

    velocity_genes = rgv.pp.preprocess_data(adata.copy()).var_names.tolist()
    tf_mask = adata.var_names[adata.uns["skeleton"].sum(1) != 0]
    var_mask = np.union1d(tf_mask, velocity_genes)
    adata = adata[:, var_mask].copy()
    adata.uns["skeleton"] = adata.uns["skeleton"].loc[
        adata.var_names.tolist(), adata.var_names.tolist()
    ]

    # rgv.pp.filter_genes can drop every gene when the prior GRN is too sparse;
    # fall back to the pre-filter gene set (min-max scaled only) in that case.
    adata_before = adata.copy()
    skeleton_before = adata.uns["skeleton"].copy()
    skipped = False
    issue_error = None
    try:
        adata = rgv.pp.filter_genes(adata)
        adata = rgv.pp.preprocess_data(adata, filter_on_r2=False)
    except Exception as exc:  # noqa: BLE001 - deliberate fallback
        skipped = True
        issue_error = exc
        adata = adata_before
        adata.uns["skeleton"] = skeleton_before
        adata.uns["network"] = skeleton_before.copy()
        adata.uns["regulators"] = adata.var_names.to_numpy()
        adata.uns["targets"] = adata.var_names.to_numpy()
        scale_status = min_max_scale_layers(adata)
        print(f"[WARN] filter_genes skipped ({exc}); min-max: {scale_status}")

    adata.var["velocity_genes"] = adata.var_names.isin(velocity_genes)
    adata.var["TF"] = adata.var_names.isin(tf_mask)

    if skipped and issue_log:
        _log_issue(issue_log, dataset_label, issue_error)

    return adata


def _log_issue(issue_log: str, dataset_label: str, error: Exception) -> None:
    try:
        Path(issue_log).parent.mkdir(parents=True, exist_ok=True)
        with open(issue_log, "a", encoding="utf-8") as handle:
            handle.write("=" * 60 + "\n")
            handle.write(f"dataset: {dataset_label}\n")
            handle.write(f"error: {type(error).__name__}: {error}\n")
            handle.write(traceback.format_exc() + "\n")
    except Exception as exc:  # noqa: BLE001
        print(f"[WARN] could not write issue log: {exc}")


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------
def train_regvelo(
    adata,
    max_epochs: int = 150,
    batch_size: Optional[int] = None,
    train_size: float = 0.8,
    soft_constraint: bool = True,
    lam: float = 1.0,
    lam2: float = 0.0,
):
    """Build and train a RegVelo model, returning it (velocity written to adata)."""
    api = load_regvelo_api()
    torch = api["torch"]
    rgv = api["rgv"]
    REGVELOVI = api["REGVELOVI"]

    weights = adata.uns["skeleton"].copy()
    weights = torch.tensor(np.array(weights).astype(np.float32)).int()
    weights = weights.T  # regulators x targets

    tf_list = adata.var_names[adata.var["TF"]]

    REGVELOVI.setup_anndata(adata, spliced_layer="Ms", unspliced_layer="Mu")

    # Structural parameters stay at RegVelo defaults; only the soft-constraint
    # strength is exposed because the model rejects the others when passed again.
    vae = REGVELOVI(
        adata,
        W=weights,
        regulators=tf_list,
        soft_constraint=soft_constraint,
        lam=lam,
        lam2=lam2,
    )

    if batch_size is None and adata.n_obs > 10000:
        batch_size = 512
        print(f"[INFO] {adata.n_obs} cells > 10000; mini-batch training (batch_size={batch_size})")

    vae.train(
        max_epochs=max_epochs,
        lr=1e-2,
        weight_decay=1e-5,
        eps=1e-16,
        train_size=train_size,
        batch_size=batch_size,
        validation_size=None,
        early_stopping=True,
        gradient_clip_val=10,
        optimizer="AdamW",
    )

    rgv.tl.set_output(adata, vae, n_samples=30, batch_size=adata.n_obs)
    return vae


def derive_output_stem(input_path: Path) -> str:
    """Strip the benchmark `_dataset` suffix from an input file stem."""
    stem = input_path.stem
    if stem.endswith("_dataset"):
        return stem[:-8]
    return stem


def run_regvelo_analysis(
    input_path,
    output_dir,
    cluster_key: str,
    dataset_name: Optional[str] = None,
    grn_parquet=None,
    pyscenic_loom=None,
    n_top_genes: int = DEFAULT_N_TOP_GENES,
    max_epochs: int = 150,
    batch_size: Optional[int] = None,
    train_size: float = 0.8,
    soft_constraint: bool = True,
    lam: float = 1.0,
    lam2: float = 0.0,
    save_model: bool = True,
    cuda: Optional[int] = None,
    seed: int = 2024,
    overwrite: bool = False,
) -> Path:
    """Run the full RegVelo pipeline for a single h5ad dataset."""
    input_path = Path(input_path)
    output_dir = Path(output_dir)
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    dataset_name = dataset_name or input_path.stem
    dataset_dir = output_dir / dataset_name
    dataset_dir.mkdir(parents=True, exist_ok=True)
    output_h5ad = dataset_dir / f"{derive_output_stem(input_path)}.h5ad"

    if output_h5ad.exists() and not overwrite:
        print(f"Skipping existing output: {output_h5ad}")
        return output_h5ad

    seed_everything(seed)
    configure_cuda(cuda)

    issue_log = os.environ.get("REGVELO_ISSUE_LOG", str(dataset_dir / "regvelo_issue_samples.txt"))

    adata = None
    try:
        print(f"\nProcessing: {input_path.name}")
        grn = load_grn(grn_parquet=grn_parquet, pyscenic_loom=pyscenic_loom)

        adata = sc.read(input_path)
        adata = preprocess_adata(
            adata,
            grn=grn,
            cluster_key=cluster_key,
            n_top_genes=n_top_genes,
            issue_log=issue_log,
            dataset_label=dataset_name,
        )
        adata.write(dataset_dir / "pp.h5ad")

        print("  Training RegVelo...")
        vae = train_regvelo(
            adata,
            max_epochs=max_epochs,
            batch_size=batch_size,
            train_size=train_size,
            soft_constraint=soft_constraint,
            lam=lam,
            lam2=lam2,
        )

        if save_model:
            model_path = dataset_dir / "regvelo_model"
            vae.save(str(model_path), overwrite=True)
            print(f"[INFO] RegVelo model saved: {model_path}")

        if "velocity" not in adata.layers:
            raise RuntimeError("RegVelo did not write layers['velocity'].")

        try:
            sc.tl.pca(adata, layer="Ms")
        except Exception as exc:  # noqa: BLE001 - PCA is best-effort
            print(f"[WARN] PCA on Ms skipped: {exc}")

        adata.uns["regvelo_run"] = {
            "dataset_name": str(dataset_name),
            "input_path": str(input_path.resolve()),
            "cluster_key": cluster_key,
            "grn_parquet": str(grn_parquet) if grn_parquet else "",
            "pyscenic_loom": str(pyscenic_loom) if pyscenic_loom else "",
            "output_path": str(output_h5ad.resolve()),
        }
        adata.write(output_h5ad, compression="lzf")
        print(f"  Done: {output_h5ad}")
        return output_h5ad
    finally:
        del adata
        cleanup_resources()


def run_batch_regvelo(
    metadata_file,
    output_dir,
    default_cluster_key: Optional[str] = None,
    grn_parquet=None,
    pyscenic_loom=None,
    n_top_genes: int = DEFAULT_N_TOP_GENES,
    max_epochs: int = 150,
    batch_size: Optional[int] = None,
    cuda: Optional[int] = None,
    seed: int = 2024,
    overwrite: bool = False,
) -> List[Path]:
    """Run RegVelo over every row of a metadata manifest."""
    metadata_file = Path(metadata_file)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    separator = "," if metadata_file.suffix.lower() == ".csv" else "\t"
    metadata_df = pd.read_csv(metadata_file, sep=separator)
    outputs: List[Path] = []
    print(f"Batch mode: {len(metadata_df)} datasets")

    for _, row in metadata_df.iterrows():
        file_path = Path(str(row["file_path"]))
        if not file_path.exists():
            print(f"Skipping missing file: {file_path}")
            continue

        cluster_key = row.get("cluster_key", default_cluster_key) or default_cluster_key
        if not cluster_key:
            print(f"Skipping {row.get('dataset_name')}: no cluster key")
            continue

        row_grn = row.get("grn_parquet", grn_parquet)
        row_loom = row.get("pyscenic_loom", pyscenic_loom)
        try:
            outputs.append(
                run_regvelo_analysis(
                    input_path=file_path,
                    output_dir=output_dir,
                    cluster_key=str(cluster_key),
                    dataset_name=str(row.get("dataset_name", file_path.stem)),
                    grn_parquet=row_grn if row_grn else None,
                    pyscenic_loom=row_loom if row_loom else None,
                    n_top_genes=n_top_genes,
                    max_epochs=max_epochs,
                    batch_size=batch_size,
                    cuda=cuda,
                    seed=seed,
                    overwrite=overwrite,
                )
            )
        except Exception as exc:  # noqa: BLE001 - keep batch runs going
            print(f"Failed: {row.get('dataset_name')}: {exc}")

    return outputs


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="RegVelo RNA velocity (real data, pySCENIC GRN prior)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument("--input", help="Input H5AD file")
    input_group.add_argument("--metadata-file", help="Metadata CSV/TSV file for batch processing")

    parser.add_argument("--output-dir", required=True, help="Output directory")
    parser.add_argument("--dataset-name", dest="dataset_name", default=None, help="Dataset folder name")
    parser.add_argument("--cluster-key", dest="cluster_key", default=None,
                        help="Column name in adata.obs used for cell-type labels")
    parser.add_argument("--grn-parquet", dest="grn_parquet", default=None,
                        help="Pre-computed pySCENIC GRN parquet (0/1 regulator-target matrix)")
    parser.add_argument("--pyscenic-loom", dest="pyscenic_loom", default=None,
                        help="pySCENIC AUCell loom; used to generate the GRN parquet when --grn-parquet is absent")
    parser.add_argument("--n-top-genes", dest="n_top_genes", type=int, default=DEFAULT_N_TOP_GENES,
                        help="Number of highly variable genes")
    parser.add_argument("--max-epochs", dest="max_epochs", type=int, default=150,
                        help="Maximum number of training epochs")
    parser.add_argument("--batch-size", dest="batch_size", type=int, default=None,
                        help="Mini-batch size (None = all cells; large datasets suggest 512)")
    parser.add_argument("--train-size", dest="train_size", type=float, default=0.8,
                        help="Fraction of cells used for training")
    parser.add_argument("--soft-constraint", dest="soft_constraint", action="store_true", default=True,
                        help="Use the soft regulatory constraint")
    parser.add_argument("--no-soft-constraint", dest="soft_constraint", action="store_false",
                        help="Disable the soft regulatory constraint")
    parser.add_argument("--lam", dest="lam", type=float, default=1.0, help="First regularization weight")
    parser.add_argument("--lam2", dest="lam2", type=float, default=0.0, help="Second regularization weight")
    parser.add_argument("--no-save-model", dest="save_model", action="store_false", default=True,
                        help="Do not save the trained RegVelo model")
    parser.add_argument("--cuda", type=int, default=None,
                        help="CUDA device id; when omitted the freest GPU is auto-selected")
    parser.add_argument("--overwrite", action="store_true", default=False, help="Overwrite existing outputs")
    parser.add_argument("--seed", type=int, default=2024, help="Random seed")
    return parser


def main(args: Optional[argparse.Namespace] = None):
    parser = build_arg_parser()
    if args is None:
        args = parser.parse_args()

    if args.metadata_file:
        return run_batch_regvelo(
            metadata_file=args.metadata_file,
            output_dir=args.output_dir,
            default_cluster_key=args.cluster_key,
            grn_parquet=args.grn_parquet,
            pyscenic_loom=args.pyscenic_loom,
            n_top_genes=args.n_top_genes,
            max_epochs=args.max_epochs,
            batch_size=args.batch_size,
            cuda=args.cuda,
            seed=args.seed,
            overwrite=args.overwrite,
        )

    if not args.cluster_key:
        parser.error("--cluster-key is required in single-file mode")
    if not args.grn_parquet and not args.pyscenic_loom:
        parser.error("provide --grn-parquet or --pyscenic-loom in single-file mode")

    return run_regvelo_analysis(
        input_path=args.input,
        output_dir=args.output_dir,
        cluster_key=args.cluster_key,
        dataset_name=args.dataset_name,
        grn_parquet=args.grn_parquet,
        pyscenic_loom=args.pyscenic_loom,
        n_top_genes=args.n_top_genes,
        max_epochs=args.max_epochs,
        batch_size=args.batch_size,
        train_size=args.train_size,
        soft_constraint=args.soft_constraint,
        lam=args.lam,
        lam2=args.lam2,
        save_model=args.save_model,
        cuda=args.cuda,
        seed=args.seed,
        overwrite=args.overwrite,
    )


if __name__ == "__main__":
    main()
